version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: party_db
    networks:
      - backend
  app:
    build: . 
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "/wait && ./party"
    networks:
      - backend

networks:
  backend:
